name: build

on: [push, pull_request]

jobs:
  build_test_connections:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image
      run: docker build -t musica .
    - name: run tests in container
      run: docker run --name test-container -t musica bash -c 'make coverage ARGS="--rerun-failed --output-on-failure"'
    - name: copy coverage from container
      run: docker cp test-container:build/coverage.info .
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.info