name: build

on: [push, pull_request]

jobs:
  build_test_connections:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image
      run: docker build -t musica .
    - name: run tests in container
      run: docker run --name test-container -t musica bash -c 'make test'
  build_test_connections_with_openmp:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image
      run: docker build -t musica-openmp -f Dockerfile.openmp .
    - name: run tests in container
      run: docker run --name test-container -t musica-openmp bash -c 'make test'
  build_test_connections_with_mpi:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image
      run: docker build -t musica-mpi -f Dockerfile.mpi .
    - name: run tests in container
      run: docker run --name test-container -t musica-mpi bash -c 'make test'